### ISSUE TITLE
Delay after breaking a lectern

### ISSUE THREAD

**Issue by arkksu** [GameduJS/EasyVillagerTrade#13]
Villager doesn't manage to lose his job before the script puts the lectern (server optimization)

https://github.com/GameduJS/EasyVillagerTrade/assets/115230995/cd4ad551-5c80-466a-a96c-d8e84bb573c7

**Comment by GameduJS** [comment]
I will have a look at it

**Comment by GameduJS** [comment]
Even though I couldn't recreate the situation in any way possible, I updated the mod in the following file so that it waits until the villager has lost its job.
[EasyVillagerTrade-1.2-1.20.zip](https://github.com/GameduJS/EasyVillagerTrade/files/12113261/EasyVillagerTrade-1.2-1.20.zip)
**Could you test it?**

It might also have been, that the villager you tried had already been locked, but the clip wasn't that informative to tell.

**Comment by arkksu** [comment]
yep, it works fine. Villager wasn't locked, it's server optimization mod which makes villagers tick less often

**Comment by GameduJS** [comment]
That's good, thank you for reviewing the update so fast.
I will update the mod as soon as possible on Github and Modrinth.
